# Configuration settings you cannot change
# see https://help.github.com/articles/using-jekyll-with-pages/
#
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
 noscript: false

# Formatting
markdown: redcarpet
redcarpet:
  extensions: [
    "autolink"
  , "tables"
  , "strikethrough"
  , "with_toc_data"
  , "fenced_code_blocks"
  , "no_intra_emphasis"
  ]

# Permalinks
permalink: pretty

# File inclusion (these would otherwise be hidden)
include: ["_assets", "_search.json"]

exclude: [CNAME, Gemfile, Gemfile.lock, Makefile, README.md, LICENSE, vendor, robots_*, linklint]

baseurl:
title:        ParkU
tagline:      A Developers Guide To Parking
description:
url:          http://developer.parku.ch

author:
  name:       Danilo Braband
  url:        https://github.com/dabio

parku:
  url:        https://parku.ch
  api:        https://parku.ch/v4
