# Group Doors
Access needs a __private key__.

## Doors Actions [/bookings/{booking_id}/doors/open]

This endpoint is used to open doors and it opens opens all the doors for the booking. A private key is needed.


### Open Doors [GET /bookings/{booking_id}/doors/open]

+ Parameters
    + booking_id: `00cd7cfd-e42d-11e2-8bf1-8a83f3373875` (string,required) - the booking id

+ Request
    + Headers
            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 204
    On success.
    + Body

+ Response 404
    If there is no doors in booking location.
    + Body

+ Response 422
    If booking is not active.
    + Body
