# Group Login
## Login [/login]
Access needs a __public key__.

### Login [POST /login{?email,password}]

Checks the given credentials email and password for validity.
Returns the user object with a user token needed for private endpoints. A public key is needed.
All further requests using the token as HTTP Basic Auth username are made on behalf of the user.

Login through Facebook is described in a separate endpoint.

+ Request
    + Attributes
        + `email`: `test@example.com` (string,required) - The users email address.
        + `password`: `1234pwd` (string,required) - The users password.

    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200
    + Attributes (Login Response)

# Data Structures

## Login Response (object)
+ code: KFJ32 (string) - customer code
+ gender: male (enum[string]) - customer gender
    + Members
        + male
        + female
+ email: `test@example.com` (string) - customer email
+ firstname: Max (string) - customers first name
+ lastname: Power (string) - customers last name
+ credit: 10650 (number) - customers credit as integer number
+ Include (Currency)
+ country: CH (string) - country code of the customers origin country
+ facebook_id: 100006987966349 (string) - customers facebook id if available
+ cars (array[Car])
+ `phone_numbers` (array[Phone Number])
+ attributes (array[Attribute])
+ token: ce35e3504183c2f52f58263ce11004e0 (string) - private user token

## Car (object)
+ id: 12 (string) - car id
+ `license_place`: `B-AB 1234` (string) - the cars license plate
+ vehicle: Isetta (string) - the car type
+ country: DE (string) - the cars country if available

## Phone Number (object)
+ id: 16696 (string) - phone number id
+ `phone_number`: `099028-237489` (string) - the actual number

## Attribute (object)
+ id: 1 (string) - attribute id
+ key: adac (string) - the key of the attributes
+ value: 1234567890 (string) - the value of the attribute
