# Group Onstreet

## Onstreet [/onstreet]

### Retrieve Onstreet Zone Information [GET /onstreet{?lat,lon}]
Access needs at least a __public key__.

This request returns parking zone information about a specific point on the map.

+ Parameters
    + `lat`: 53.12341234 (number,required) - latitude of the requested point
    + `lon`: 13.12341234 (number,required) - longitude of the requested point

+ Request
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200 (application/json)
    + Attributes
        + id: `101012` (string) - the parking zone id
        + name: `Berlin 101012` (string) - the parking space zone name
        + hours: `Mon-Fri, 08:00 - 22:30` (string) - the translated availability time in this zone
        + `price.unit_cost`: `0.05` (number) - cost per unit (which is defined by `unit_interval_minutes`)
        + `price.unit_interval_minutes`: 3 (number) - how many minutes one unit is
        + `price.currency`: EUR (enum) - the currency of the price
            + Members
                + EUR
                + CHF
        + `max_datetime_end`: `2009-06-30T18:30:00+02:00` (string) - datetime when a booking has to end
        + `duration_max`: `2 hours` (string) - translated string of maximum general parking duration
        + `available_payment_methods`: `['paypal', 'credits']` (array[string]) - available payment methods
        + `available_payment_types`: [`post`] (array[string]) - available payment types
    + Body

            {
               id: "101012",
               name: "Berlin 101012",
               hours: "Mon-Fri, 08:00 - 22:30",
               price: {
                 unit_cost: 0.05,
                 unit_interval_minutes: 3,
                 currency: "EUR",
                 transaction_fee: 0.25,
               },
               date_end: "2016-11-29...",
               duration_max: "2 hrs",
               available_payment_methods: ['paypal', 'credits']
               available_payment_types: ['post']
            }

### Start an Onstreet Booking [POST /onstreet/start]
Access needs at least a __private key__.

Bookings can be stopped using the [Stop a Booking](#bookings-bookings-post-3) action.

+ Request (application/x-www-form-urlencoded)
    + Attributes
        + `lat`: 53.12341234 (number,required) - latitude of the requested point
        + `lon`: 13.12341234 (number,required) - longitude of the requested point
        + `unit_cost`: 0.05 (number,required) - the cost per unit in `currency`
        + `unit_interval_minutes` (number,required) - number of minutes per unit
        + `currency`: `EUR`(enum[string],required) - the currency the cost information is in
            + Members
                + EUR
                + CHF
        + `payment_methods`: paypal, credits (array[enum],required) - array containing the planned payment methods for this booking
        + `payment_type` (enum[string],required) - payment type
            + Members
                + immediate
                + post
        + `license_plate`: `AB 1234` (string,required) - the license plate of the car used for parking
        + `phone_number`: `01234567890` (string,required) - the customer phone number
        + `start`: `2009-06-30T18:30:00+02:00` (string,required) - the start date of the booking

+ Response 201 (application/json)
    + Attributes
      + `id`: `0000bb3e-506d-11e5-9781-d43d7eece658` (string) - the booking id
      + `zone` (string) - a onstreet zone object as returned by the [Retrieve Onstreet Zone Information](#onstreet-onstreet-get) Request.
    + Body

            {
               id: "0000bb3e-506d-11e5-9781-d43d7eece658",
               zone:
               {
                 id: "101012",
                 name: "Berlin 101012",
                 hours: "Mon-Fri, 08:00 - 22:30",
                 price: {
                   unit_cost: 0.05,
                   unit_interval_minutes: 3,
                   currency: "EUR",
                   transaction_fee: 0.25,
                 },
                 date_end: "2016-11-29...",
                 duration_max: "2 hrs",
                 available_payment_methods: ['paypal', 'credits'],
                 available_payment_types: ['post']
              }
            }
