# Group Authentication

## Http Basic Auth
Authentication to the API occurs via HTTP Basic Auth. Provide your API key as the basic auth username.
The password is always parku.
All API requests must be made over HTTPS. Calls made over plain HTTP will fail.
You must authenticate for all requests.

### Example
Curl using HTTP Basic Auth with username and password for the public token `012345678abcdef`:
```
$ curl -u 012345678abcdef:parku http://sandbox.test.parku.io/v5/
```

Same request, directly using the username and password from above encoded into Base64 inside the basic auth header:
```
$ curl -H 'Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1' http://sandbox.test.parku.io/v5/
```

## Private and public tokens
There are two types of tokens: public and private. Public tokens are used to obtain publicly available
information (eg. parking spaces). Private tokens are used to identify users.
Whenever user information are requested or bookings on behalf of a user is made, the private key is necessary.

## Retrieving a private token
You retrieve a user specific private key by logging in as a user.

## Private vs. public urls
For the public urls you need a public key. With a private key you can access public urls.
