# Group Coupon
## Coupon [/coupon]

### Test a Coupon [GET /coupon/{encoded_code}{?action,amount}]
#### Response
+ Parameters
    + `encoded_code`: Zm9vYmFyMTIz (string, required) - A base64url encoded coupon code string.
    + action: test (enum, required) - Action to do.
        + Members
            + test
    + amount: 42 (number, required) - Amount coupon has to be tested against.

+ Response 200
|           |                                         |
|-----------|-----------------------------------------|
| code      | `string` Decoded, sanitized coupon code |
| value     | `number` Coupons value                  |
| deduction | `number` Amount used of coupon value    |
    + Body

            {
              "code": "foobar123",
              "value": 10,
              "deduction": 10
            }

+ Response 422
| Code |                                         Description                                         |
|------|---------------------------------------------------------------------------------------------|
| 10   | "amount" is faulty, probably below 0.                                                       |
| 30   | Coupon quota exhausted.                                                                     |
| 31   | User usage quota for this coupon is exhausted.                                              |
| 32   | User usage quota for a coupon is same grouping is exhausted.                                |
| 40   | Platform (Android, iOS, web) is not enabled. Some coupons only work on specific a platform. |
    + Body

            {
              "errors": [
                {
                  "field": "coupon",
                  "code": 31,
                  "message": "Coupon usage exceeded."
                }
              ]
            }

+ Response 404
| Code |                                         Description                                         |
|------|---------------------------------------------------------------------------------------------|
| 20   | Coupon not found.                                                                           |
| 21   | Coupon is inactive.                                                                         |
| 22   | Coupon expired.                                                                             |
| 23   | Coupon date (start or end) prohibit coupon usage.                                           |
    + Body

            {
              "errors": [
                {
                  "field": "coupon",
                  "code": 20,
                  "message": "Coupon not found."
                }
              ]
            }
