FORMAT: 1A
HOST: https://parku.ch/v4

# Parku API v4 Reference
<!-- include(attributes.apib) -->
<!-- include(bookings.apib) -->
<!-- include(cars.apib) -->
<!-- include(coupon.apib) -->
<!-- include(devices.apib) -->
<!-- include(facebook.apib) -->
<!-- include(invitations.apib) -->
<!-- include(locations.apib) -->
<!-- include(login.apib) -->
<!-- include(password.apib) -->
<!-- include(payment.apib) -->
<!-- include(phone_numbers.apib) -->
<!-- include(sesam.apib) -->
<!-- include(settings.apib) -->
<!-- include(static_pages.apib) -->
<!-- include(user.apib) -->
<!-- include(violations.apib) -->
<!-- include(voucher.apib) -->

# Group Changelog
<!-- include(changelog.md) -->
