FORMAT: 1A
HOST: https://parku.de/v4

# Parku API v4 Reference

## Group Locations
<!-- include(locations.apib) -->

## Group Bookings
<!-- include(bookings.apib) -->
<!-- include(violations.apib) -->

## Group User
<!-- include(user.apib) -->
<!-- include(login.apib) -->
<!-- include(facebook.apib) -->
<!-- include(password.apib) -->
<!-- include(payment.apib) -->
<!-- include(cars.apib) -->
<!-- include(devices.apib) -->
<!-- include(phone_numbers.apib) -->

## Group Sesam
<!-- include(sesam.apib) -->

## Group Settings
<!-- include(settings.apib) -->

## Group Miscellaneous
<!-- include(invitations.apib) -->
<!-- include(attributes.apib) -->
<!-- include(coupon.apib) -->
<!-- include(voucher.apib) -->
<!-- include(static_pages.apib) -->

## Group Changelog
<!-- include(changelog.md) -->
