# Group Password
## Password [/password]

### Update password [GET /password{?old_password,new_password}]

+ Parameters
    + `old_password`: pwd123 (string,required) - The current active password.
    + `new_password`: pwd321 (string,required) - The new password.


+ Request

            $ curl https://parku.ch/{{apiversion}}/password \
            -u 098f6bcd4621d373cade4e832627b4f6:parku \
            -X PUT \
            -d old_password=pwd123 \
            -d new_password=pwd321

    + Headers

            Authorization: Basic private_key:parku

+ Response 204

### Reset password [GET /password{?for}]
This sends an email with the newly set password to the users email address.

+ Parameters
    + `for`: `test@example.com` (string,required) - A valid email address of the user.


+ Request

            $ curl https://parku.ch/{{apiversion}}/password?for=test@example.com \
            -u 098f6bcd4621d373cade4e832627b4f6:parku

    + Headers

            Authorization: Basic public_key:parku

+ Response 204

+ Response 404
The given email address is not found in the database.
    + Body
