# Group Phone Numbers
## Phone Numbers [/phone_numbers]
Access needs a __private key__.

### List all Phone Numbers [GET /phone_numbers]
Returns a list of all phone numbers of the user.
The phone numbers are returned sorted by creation date, with the most recently created phone number appearing first.

+ Request
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200 (application/json)
    + Body

            [
              {
                "id": 150,
                "phone_number": "+493057701872"
              },
              {
                "id": 149,
                "phone_number": "+493057701871"
              },
              {...},
              {...}
            ]


### Create a New Phone Number [POST /phone_numbers]
You can store multiple phone numbers for a user.

#### Body Parameters
+ Request (application/x-www-form-urlencoded)
    + Attributes
        + `phone_number`: `+493057701873` (string,required) - The phone number.
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 201 (application/json)
    + Body

            {
                "id": "151",
                "phone_number": "+493057701873"
            }

### Retrieve a Phone Number [GET /phone_numbers/{phone_number_id}]

+ Parameters
    + `phone_number_id`: 151 (number,required) - The identifier of the phone number to be retrieved.

+ Request
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200 (application/json)
    + Body

            {
              "id": 151,
              "phone_number": "+493057701873"
            }

### Update a Phone Number [PUT /phone_numbers/{phone_number_id}]
#### Body Parameters
+ Request (application/x-www-form-urlencoded)
    + Attributes
        + `phone_number_id`: 151 (number,required) - The identifier of the phone number to be updated.
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200 (application/json)
    + Body

            {
              "id": 151,
              "phone_number": "+493057701874"
            }

### Delete a Phone Number [DELETE /phone_numbers/{phone_number_id}]
+ Parameters
    + `phone_number_id`: 151 (number,required) - The identifier of the phone number to be deleted.

+ Request
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200
