# Static Pages [/]

## Terms and Conditions [GET /terms]

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...

## Imprint [GET /imprint]

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...

## Privacy Policy [GET /privacy_policy]

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...
