# Group Static Pages
Access needs at least a __public key__.

## Static Pages [/terms]
### Retrieve Terms and Conditions [GET /terms]

+ Request
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...

## Static Pages [/imprint]
### Retrieve Imprint [GET /imprint]

+ Request
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...

## Static Pages [/privacy_policy]
### Retrieve Privacy Policy [GET /privacy_policy]

+ Request
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...
