# Group Static Pages
## Static Pages [/]

### Terms and Conditions [GET /terms]

+ Request

            $ curl https://parku.ch/{{apiversion}}/terms \
            -u 6f1ed002ab5595859014ebf0951522d9:parku

    + Headers

            Authorization: Basic MTIzNDU2Nzg5MDpwYXJrdQ==

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...

### Imprint [GET /imprint]

+ Request

            $ curl https://parku.ch/{{apiversion}}/imprint \
            -u 6f1ed002ab5595859014ebf0951522d9:parku

    + Headers

            Authorization: Basic MTIzNDU2Nzg5MDpwYXJrdQ==

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...

### Privacy Policy [GET /privacy_policy]

+ Request

            $ curl https://parku.ch/{{apiversion}}/privacy_policy \
            -u 6f1ed002ab5595859014ebf0951522d9:parku

    + Headers

            Authorization: Basic MTIzNDU2Nzg5MDpwYXJrdQ==

+ Response 200 (application/xhtml+xml)
    + Body

            <!DOCTYPE html>
                <html xmlns="http://www.w3.org/1999/xhtml"...
