# Group Voucher
## Voucher [/voucher]
Access needs a __private key__.

__DEPRECATED__ This resource is deprecated and will be removed in __v5__. Use coupons instead.

### Redeem a Voucher [PUT /voucher]
#### Body Parameters
+ Request (application/x-www-form-urlencoded)
    + Attributes
        + `voucher`: `parkieren12` (string,required)
        + `device_id`: `asdf1234` (string,optional) - The ID of the mobile device (usually the IMEI) when voucher code
            can only be used once per device.
    + Headers

            Authorization: Basic MDEyMzQ1Njc4YWJjZGVmOnBhcmt1

+ Response 200
    + Body

            {
              "gender": "female",
              "email": "test@example.com",
              "firstname": "Test",
              "lastname": "Name",
              "credit": 5.0,
              "currency": "EUR",
              "country": "DE",
              "facebook_id": null,
              "token": "098f6bcd4621d373cade4e832627b4f6"
            }
